package pojos;
// Generated 23 ene. 2025 9:06:45 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Proxecto generated by hbm2java
 */
@Entity
@Table(name = "PROXECTO",
         schema = "dbo",
         catalog = "EmpresaHB",
         uniqueConstraints = @UniqueConstraint(columnNames = "Nome_proxecto")
)
public class Proxecto implements java.io.Serializable {
    @Id
    @Column(name = "Num_proxecto", unique = true, nullable = false)
    private int numProxecto;
    
    @Column(name = "Nome_proxecto", unique = true, nullable = false, length = 25)
    private String nomeProxecto;
    
    @Column(name = "Lugar", nullable = false, length = 25)
    private String lugar;

    public Proxecto() {
    }

    public Proxecto(int numProxecto, String nomeProxecto, String lugar) {
        this.numProxecto = numProxecto;
        this.nomeProxecto = nomeProxecto;
        this.lugar = lugar;
    }

    public int getNumProxecto() {
        return this.numProxecto;
    }

    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }

    public String getNomeProxecto() {
        return this.nomeProxecto;
    }

    public void setNomeProxecto(String nomeProxecto) {
        this.nomeProxecto = nomeProxecto;
    }

    public String getLugar() {
        return this.lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    @Override
    public String toString() {
        return "Proxecto{" + "numProxecto=" + numProxecto + ", nomeProxecto=" + nomeProxecto + ", lugar=" + lugar + '}';
    }
}
